### ISSUE TITLE
Broken link to ScienceBase scanner

### ISSUE THREAD

**Issue by hmaier-fws** [USFWS/Science_Applications_Metadata_Guidance#5]
The Trouble-Shooting: Overview page (https://usfws.github.io/Science_Applications_Metadata_Guidance/content/trouble_shooting/trouble_shooting_overview.html) contains a broken link to "ScienceBase scanner" (http://calcommons.info/sb2/scansb.php)

**Comment by blakemassey-usfws** [comment]
That link is not longer working because the website is defunct. Removed that section in the Guidance, so the issue is resolved.

**Comment by blakemassey-usfws** [comment]
That link is not longer working because the website is defunct. Removed that section in the Guidance, so the issue is resolved.
