### ISSUE TITLE
Add additional methods to submit comments or issues

### ISSUE THREAD

**Issue by hmaier-fws** [USFWS/Science_Applications_Metadata_Guidance#6]
The guidance presents two options on the right sidebar: "Edit this page" and "Report an issue". Both methods present the user with a "Sign in to GitHub" dialog. This may prevent users without a GitHub account from submitting comments.

Consider adding other methods for submitting comments or issues. Perhaps:
  - Edit this page
  - Report an issue in GitHub
  - Report an issue or submit a comment (via email)

The guidance may be used by a broad audience including FWS staff without a GitHub account and non-FWS staff who may, or may not have a GitHub account. Expanding the options for submitting comments will allow input to be received from a broader aaudience.

**Comment by blakemassey-usfws** [comment]
Replaced the right sidebar options with a single choice to use the new [Feedback Form](https://forms.office.com/g/xtkDZ3rQjW). This should simplify the options for people and not confuse the casual (non-Github) users. 
The Github users can still provide feedback via the **Provide Feedback** sections in the [Introduction](https://usfws.github.io/Science_Applications_Metadata_Guidance/#provide-feedback).

**Comment by blakemassey-usfws** [comment]
Will consider this fixed for now, but may want to update or remove the options based on users' experience.
